name: AccessoriesPlugin
version: 1.0.0
main: io.papermc.testplugin.ExamplePlugin
description: An accessories plugin
author: RysKowalski
website: https://papermc.io
api-version: "1.21.11"

commands:
  aglet:
    description: give user oak log named Aglet
    usage: /aglet
  akcesoria:
    description: open Akcesoria gui
    usage: /akcesoria
