name: ExamplePlugin
version: 1.0.0
main: io.papermc.testplugin.ExamplePlugin
description: An example plugin
author: PaperMC
website: https://papermc.io
api-version: "1.21.11"

commands:
  hello:
    description: WTH do you want
    usage: /hello
  aglet:
    description: give user oak log named Aglet
    usage: /aglet
